name: shared
description: "-"
version: 0.0.0
publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    http: ^1.1.0

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
